- name: Install Ifupdown
  package:
    name:
      - "ifupdown"
    state: latest

- name: Enable WakeonLan with Ethtool
  ansible.builtin.shell:
    cmd: "sudo ethtool -s enp30s0 wol g"

- name: Keep the wakeonlan presistent on boot
  ansible.builtin.lineinfile:
    path: /etc/network/interfaces
    insertafter: "EOF"
    line: "auto lo\niface lo inet loopback\n\nauto enp30s0\niface enp30s0 inet static\n    address 192.168.1.101\n    netmask 255.255.255.0\n    gateway 192.168.1.1\n    up ethtool -s enp30s0 wol g\n"

