- name: Install Ifupdown
  package:
    name:
      - "ifupdown"
    state: latest

- name: Enable WakeonLan with Ethtool
  ansible.builtin.shell:
    cmd: "sudo ethtool -s enp30s0 wol g"

- name: Keep the wakeonlan presistent on boot
  ansible.builtin.blockinfile:
    path: /etc/network/interfaces
    block: |
      auto lo
      iface lo inet loopback

      auto enp30s0
      iface enp30s0 inet static
          address 192.168.1.101
          netmask 255.255.255.0
          gateway 192.168.1.1
          up ethtool -s enp30s0 wol g

# - name: Testing lineinfine
#   ansible.builtin.blockinfile:
#     path: /home/tzen/test.md
#     block: |
#       Change this or 
#       that 
#       or don't do anying at all
#         or lol
#             this is troll
